require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rake
  - rubocop-factory_bot
  - rubocop-i18n

AllCops:
  NewCops: enable
  Exclude: 
    - bin/**/*
    - db/**/*
Style/Documentation:
  Enabled: false

