require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rake
  - rubocop-factory_bot
  - rubocop-i18n

AllCops:
  NewCops: enable
  Exclude: 
    - bin/**/*

Metrics/AbcSize:
  Exclude:
    - db/**/*

Metrics/MethodLength:
  Exclude:
    - db/**/*

Metrics/BlockLength:
  Exclude:
    - db/**/*

Style/Documentation:
  Enabled: false

