require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rake
  - rubocop-factory_bot
  - rubocop-i18n

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2
  Exclude: 
    - bin/**/*
    - vendor/**/*
    - vendor/bundle/**/*
    - gemfiles/vendor/bundle/**/*
  Include: 
    [ Gemfile ]
Style/Documentation:
  Enabled: false

