---
version: "3.9"
services:
  app:
    build: .
    ports: 
      - 3000:3000
    volumes: 
      - bundler_gems:/home/biddy/gems
      - .:/home/biddy/web
      - tmp:/home/biddy/tmp
      - log:/home/biddy/log
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      - db
    command:  bin/rails server -p 3000 -b 0.0.0.0
  db:
    image: postgres:14.2
    ports:
      - 5432:5432
    volumes:
      - biddy-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
  sidekiq:
    build:
      context: .
    volumes: 
      - bundler_gems:/home/biddy/gems
      - .:/home/biddy/web
    command: bin/bundle exec sidekiq
    depends_on: 
     - redis
    environment: 
      REDIS_URL: 'redis://redis:6379/0'
  redis:
    image: redis:7.0
    ports: 
      - 6379:6379
    volumes: 
      - biddy-redis:/var/lib/redis/data
volumes:
  tmp:
  log:
  biddy-db:
  biddy-redis:
  bundler_gems:

