version: '3.8'
services:
  db:
    image: postgres:12
    user: "${UID}:${GID}"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  redis:
    image: 'redis:6.0'

  app:
    build: .
    user: "${UID}:${GID}"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: "redis://redis:6379/0"

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: "redis://redis:6379/0"
