[build]
builder = "nixpacks"
buildCommand = "make build && make install && make db-create && make migration"

[deploy]
startCommand = "make start"
# healthcheckPath = "/health"
# healthcheckTimeout = 100
# restartPolicyType = "never"
