# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "CI"
on: 
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    name: "RSpec"
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Prepare Env
        run: |
          echo "POSTGRES_USER=$POSTGRES_USER" >> .env
          echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
          echo "POSTGRES_HOST=$POSTGRES_HOST" >> .env
          echo "POSTGRES_PORT=$POSTGRES_PORT" >> .env
          echo "DATABASE_URL=postgresql://postgres:postgres@db:5432/biddy_test" >> .env

      - name: Run tests
        run: docker compose up db && make db-create && make migrate && make test
  lint:
    name: "Rubocop"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Prepare Env
        run: |
          echo "POSTGRES_USER=$POSTGRES_USER" >> .env
          echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
          echo "POSTGRES_HOST=$POSTGRES_HOST" >> .env
          echo "POSTGRES_POST=5432" >> .env
      - name: spin up env
        run: make lint
