# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "CI"
on: 
  pull_request:
    branches: [ "master" ]
jobs:
  setup-env:
    runs-on: ubuntu-latest
    outputs:
      env-file: ${{ steps.create-env.outputs.env-file }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare Env
        id: create-env
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" > .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env
          echo "RAILS_ENV=test" >> .env
          echo "::set-output name=env-file::$(cat .env)"
  test:
    name: "RSpec"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare Env
        run: echo "${{ needs.setup-env.outputs.env-file }}" > .env
      - name: Run tests
        run: |
          make db-create
          make migration
          make test
  lint:
    name: "Rubocop"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Prepare Env
        run: echo "${{ needs.setup-env.outputs.env-file }}" > .env
      - name: Run rubocop
        run: make lint
  brakeman:
    name: "Brakeman"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Prepare Env
        run: echo "${{ needs.setup-env.outputs.env-file }}" > .env
      - name: Run brakman
        run: make brakeman
  active_record_doctor:
    name: "AR Doctor"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Prepare Env
        run: echo "${{ needs.setup-env.outputs.env-file }}" > .env
      - name: Run doctor
        run: |
          make db-create
          make migration

