# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "CI"
on: 
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    name: "RSpec"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare Env
        run: |
          chmod -R 777 .
          env >> .env
          echo "POSTGRES_USER=${{ vars.POSTGRES_USER }}" > .env
          echo "POSTGRES_PASSWORD=${{ vars.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_HOST=${{ vars.POSTGRES_HOST }}" >> .env
          echo "POSTGRES_PORT=${{ vars.POSTGRES_PORT }}" >> .env
          echo "RAILS_ENV=test" >> .env
          echo "CC_TEST_REPORTER_ID=${{ secrets.CC_TEST_REPORTER_ID}}" >> .env
      - name: Run tests
        run: |
          make db-create
          make migration
          make test
          ls -al coverage
      - name: Store coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage_report
          path: coverage
  lint:
    name: "Rubocop"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare Env
        run: touch .env
      - name: Run rubocop
        run: make lint
  brakeman:
    name: "Brakeman"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare Env
        run: touch .env
      - name: Run brakman
        run: make brakeman
  active_record_doctor:
    name: "AR Doctor"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare Env
        run: |
          chmod -R 777 .
          echo "POSTGRES_USER=${{ vars.POSTGRES_USER }}" > .env
          echo "POSTGRES_PASSWORD=${{ vars.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_HOST=${{ vars.POSTGRES_HOST }}" >> .env
          echo "POSTGRES_PORT=${{ vars.POSTGRES_PORT }}" >> .env
          echo "RAILS_ENV=test" >> .env
      - name: Run doctor
        run: |
          make install
          make db-create
          make migration
          make doctor
  coverage:
    needs: [ test ]
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code1
        uses: actions/checkout@v4
      - name: Download coverage
        uses: actions/download-artifact@v3
        with:
          name: coverage_report
          path: coverage
      - name: Check
        run: |
          ls -al
      - name: Fetch reporter
        run: |
          curl -L codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -o test_reporter
          chmod +x test_reporter
          ls -al
      - name: Upload report
        run: |
          # ./test_reporter before-build
          ./test_reporter format-coverage -t simplecov -p /home/biddy/web
          ls -al coverage
          ./test_reporter upload-coverage
